name = "your-project-name"
type = "javascript"

[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "14"

[site]
  bucket = "./public"
  entry-point = "index.html"
  error-page = "404.html"
